_target_: lfads_torch.band_model.BAND

# --------- architecture --------- #
encod_data_dim: 8
encod_seq_len: 512
recon_seq_len: 512
ext_input_dim: 0
ic_enc_seq_len: 0
ic_enc_dim: 64
ci_enc_dim: 64
ci_lag: 1
con_dim: 64
co_dim: 4
ic_dim: 64 # 50 in autoband paper
gen_dim: 64
fac_dim: 32
causal_con: False

# --------- readin / readout --------- #
readin:
  - _target_: torch.nn.Identity
readout:
  _target_: torch.nn.ModuleList
  modules:
    - _target_: lfads_torch.modules.readin_readout.FanInLinear
      in_features: ${model.fac_dim}
      out_features: ${model.encod_data_dim}
behavior_readout:
  _target_: lfads_torch.modules.readin_readout.FanInSeq2Seq_BCI
  in_features: ${model.fac_dim}
  out_features: 20
  time_features: ${model.encod_seq_len}
  bci_time_features: 128
  dropout_rate: 0.5

# --------- augmentation --------- #
train_aug_stack:
  _target_: lfads_torch.modules.band_augmentations.AugmentationStack
  transforms:
    - _target_: lfads_torch.modules.band_augmentations.CoordinatedDropout
      cd_rate: 0.3
      cd_pass_rate: 0.0
      ic_enc_seq_len: ${model.ic_enc_seq_len}
    - _target_: lfads_torch.modules.band_augmentations.BandRotation
      min_angle: 1
      max_angle: 10
  batch_order: [0]
  loss_order: [0]
infer_aug_stack:
  _target_: lfads_torch.modules.band_augmentations.AugmentationStack

# --------- priors / posteriors --------- #
reconstruction:
  - _target_: lfads_torch.modules.recons.MSE
behavior_reconstruction:
  - _target_: lfads_torch.modules.recons.MSE
variational: True
co_prior:
  _target_: lfads_torch.modules.priors.MultivariateNormal
  mean: 0
  variance: 0.1
  shape: ${model.co_dim}
ic_prior:
  _target_: lfads_torch.modules.priors.MultivariateNormal
  mean: 0
  variance: 0.1
  shape: ${model.ic_dim}
ic_post_var_min: 1.0e-4

# --------- misc --------- #
dropout_rate: 0.1
cell_clip: 5.0
loss_scale: 1.0
recon_reduce_mean: False
behavior_weight: 0.1

# --------- learning rate --------- #
lr_init: 4.0e-3
lr_stop: 1.0e-5
lr_decay: 0.95
lr_patience: 6
lr_adam_beta1: 0.9
lr_adam_beta2: 0.999
lr_adam_epsilon: 1.0e-7
lr_scheduler: True

# --------- regularization --------- #
weight_decay: 0.0
l2_start_epoch: 0
l2_increase_epoch: 20
l2_ic_enc_scale: 0.0
l2_ci_enc_scale: 0.0
l2_gen_scale: 0.0001
l2_con_scale: 0.01
kl_start_epoch: 0
kl_increase_epoch: 20
kl_ic_scale: 1. 
kl_co_scale: 256. 
kl_ic_target: 0.
kl_co_target: 0.

