_target_: lfads_torch.band_datamodules.BasicDataModule
datafile_pattern: ${relpath:datasets/Chewie_CO_FF_2016-10-07_session_vel_all_spikes_go.h5}
fold: !!null
batch_keys:
  - behavior
attr_keys:
  - train_inds
  - valid_inds
  - train_epoch
  - valid_epoch
  - train_pos
  - valid_pos
  - train_vel
  - valid_vel
  - train_target_direction
  - valid_target_direction
batch_size: 256
sv_seed: 0
