_target_: lfads_torch.band_datamodules.BasicDataModule
datafile_pattern: ${relpath:datasets/multitask_20140725_*.h5}
fold: !!null
batch_keys:
  - behavior
attr_keys:
  - train_inds
  - valid_inds
  - train_pos
  - valid_pos
  - train_vel
  - valid_vel
  - train_force
  - valid_force
  - train_target_direction
  - valid_target_direction
  - train_epoch
  - valid_epoch
batch_size: 256
sv_seed: 0
